function alert_bolnice_text(){
	var alert_txt1_sr = 'Устаљени појам Ваљевска болница, бар када је реч о времену првих година Великог рата, није везан за неки конкретан болнички објекат нити за болницу као институцију, већ означава склоп специфичних догађаја услед којих је цео град постао једна велика болница.\n\nУ ратним плановима Краљевине Србије било је предвиђено да Ваљево, због стратешког положаја, као и због постојања гарнизона, буде један од главних центара војног санитета. Град на Колубари је овакву улогу имао и током балканских ратова, када су места борбених дејстава била удаљена од њега, да би са почетком Првог светског рата и сукоба на блиској дринској граници та улога добила додатни значај; Ваљево је постало седиште две сталне и шест резервних болница, распоређених у више десетина различитих објеката широм града.\n\n';
	
	var alert_txt2_sr = 'Током првих ратних месеци (јули – новембар) 1914. године у ваљевским болницама су збрињавани рањени у првој и другој непријатељској офанзиви. Овај период је, због бројних страдалих, био прожет веома тешким тренуцима, нарочито током друге офанизиве када је стање у граду додатно отежано не само приливом великог броја рањеника већ и бројних избеглица. Ваљево већ тада постаје град – болница. У насељу које је са својом најужим околином имало око 8.000 житеља у појединим тренуцима је боравило више десетина хиљада људи. Ипак, и поред огромних потешкоћа, српски санитет се, уз подршку грађана Ваљева и страних лекарских мисија, суочавао са више или мање очекиваним проблемима са којима је имао искуства: различити видови рана од метака и шрапнела и болести као што су трбушни тифус, дизентерија, рекуренс... Постоје индиције да се у појединачним случајевима већ тада појавио и пегави тифус, али тада нису уочене назнаке које би указале на претњу епидемије.\n\n';
	
	var alert_txt3_sr = 'После треће аустроугарске офанзиве, краткотрајног освајања (16. новембар – 9. децембар) и велике српске победе у Колубарској бици, са повратком војске и становништва у ослобођени град, Ваљево се суочило са страхотама епидемије пегавог тифуса енормих размера, за коју здравствена служба није припремљена, а која је била додатно закомпликована ескалацијом и других болести, пре свега рекуренса и трбушног тифуса. У овим трагичним тренуцима, борећи се са последицама пошасти, српско санитетско особље је уз помоћ страних лекарских мисија, грађана и ратних заробљеника, неговало знатно више болесних и рањених српских војника и цивила и заробљених припадника аустроугарске војске, него што је Ваљево имало становника. Док је у целој  Србији оболело преко пола милиона људи, а број умрлих војника, цивила и заробљеника процењен на преко 170.000, сматра се да је током трајања епидемије (децембар 1914. – мај 1915.), у Ваљеву и његовој околини умрло више од 3.500 војника, 4.000 цивила и око 2.000 заробљеника. У јеку епидемије умирало је дневно 100, 150, па и знатно више оболелих. Међу њима су били и многи лекари и болничари. Био је то период због кога су Ваљево и његове болнице постали симболи страдања, али и пожртвованости, хуманости и међународне сарадње.\n\n';
	
	var alert_txt4_sr = 'У спомен на велика ратна страдања током епидемије тифуса 1914/15. године  Народни музеј Ваљево је припремио изложбу Ваљево 1914-1915. године – град болница којој основну наративну нит презентације представљају дневничке и мемоарске белешке странаца који су у то време боравили у Ваљеву.\n\nИзложба је посвећена свим жртвама, као и свима који су помогли да се епидемија победи, без обзира на којој страни су ушли у рат, јер су се у Ваљеву сви они нашли у истим редовима и на заједничком задатку - борби против страховите пошасти.\n\n';
	
	var alert_txt1_en = 'Well-known, generally accepted term Valjevo Hospital, at least when it comes to the early years of the Great War, is not linked to any specific hospital building nor hospital as institution, but refers to a series of connected events due to which the whole town became one big hospital.\n\nIn the war plans of the Kingdom of Serbia Valjevo, because of its strategic position and the existence of the garrison, was intended to be one of the major military medical centers. The town on the Kolubara River had this role during the Balkan wars, when the combat operations were conducted away from the town. With the beginning of the First World War and the conflict at the Drina River border, this role became even more significant; Valjevo became the location of two permanent and six auxiliary hospitals, situated in dozens of different buildings throughout the city.';
	
	var alert_txt2_en = 'In the first months of the war (July - November 1914) the wounded in the war activities during the first and second Austro - Hungarian offensives were taken care of in Valjevo hospitals. This period, due to the numerous casualties, was imbued with the very difficult moments, especially during the second offensive when the situation in the town was further worsened not only by the influx of a large number of the wounded but also by numerous refugees. Valjevo had become a town - hospital by that time. The place which, with its closest surroundings, had the population of about 8,000, at times was a residing place to dozens of thousands of people. However, despite the enormous difficulties, Serbian medical corps, with the support of the citizens of Valjevo and foreign medical missions, faced with more or less expected, already experienced problems: various types of wounds from bullets and shrapnel, and diseases such as abdominal typhus, dysentery, recurring typhus ... There were indications that as early as that spotted typhus fever appeared in individual cases, but there were no signs to indicate the threat of epidemics.';
	
	var alert_txt3_en = 'Following the third Austro-Hungarian offensive, short-term conquest (15 November - 9 December) and the glorious victory in the Battle of Kolubara, with the return of the army and the population to the liberated town, Valjevo faced the horrors of the large-scale spotted typhus fever epidemic, for which the health service was not prepared and which was further complicated by the escalation of other diseases, primarily recurring typhus and abdominal typhus. In these tragic moments, struggling with the consequences of the pestilence, Serbian medical personnel, with the help of foreign medical missions, citizens and prisoners of war, provided medical care to significantly more sick and wounded Serbian soldiers, civilians and captured members of the Austro-Hungarian army than Valjevo had residents. While in the whole of Serbia over half a million people contracted the disease and the number of dead soldiers, civilians and prisoners was estimated at over 170,000, it is believed that during the epidemic (December 1914 - May 1915), more than 3,500 soldiers, 4,000 civilians and about 2,000 prisoners died in Valjevo and its surroundings. At the height of the epidemic 100 or even more ill people died on a daily basis. Among them were many doctors and nurses. It was the period which made Valjevo and its hospitals symbols not only of suffering, but also of sacrifice, humanity and international cooperation.';
	
	var alert_txt4_en = 'In memory of the great wartime suffering during the typhus epidemic 1914/15 the National Museum of Valjevo has prepared an exhibition Valjevo 1914-1915 - Town-Hospital, in which the primary narrative thread of the presentation comprises of diary notes and memoirs of foreigners who resided in Valjevo at the time.\n\nThe exhibition is dedicated to all the victims and all those who helped to defeat the epidemic, regardless of which side they entered the war on, since in Valjevo they all found themselves in the same ranks and on a common task - the fight against the terrible pestilence.';

	switch (jezik){
		case 1:
			alert (alert_txt1_sr);
			alert (alert_txt2_sr);
			alert (alert_txt3_sr);
			alert (alert_txt4_sr);
		break;
		case 2:
			alert (alert_txt1_en);
			alert (alert_txt2_en);
			alert (alert_txt3_en);
			alert (alert_txt4_en);
		break;
	}
};

